### ISSUE TITLE
9 sancus-step runs in succession cause a memory violation

### ISSUE THREAD

**Issue by martonbognar** [sancus-pma/sancus-support#9]
If `__ss_start()` is called 9 times in a program, it causes a memory violation on the last run.

A minimal program to reproduce the issue:
```c
#include <msp430.h>
#include <sancus/sm_support.h>
#include <sancus_support/sm_io.h>
#include <sancus_support/sancus_step.h>

DECLARE_SM(foo, 0x1234);

void SM_ENTRY(foo) dummy(void) {
    __asm__ __volatile__("nop\n\t":::);
}

void checkCounter(void)
{
    __asm__ __volatile__("nop\n\tnop\n\t":::);
}

int main()
{
    msp430_io_init();
    asm("eint\n\t");
    sancus_enable(&foo);

    for (int i = 0; i <= 11; ++i) {
        __ss_start();
        dummy();
    }

    EXIT();
}

/* ======== TIMER A ISR ======== */
SANCUS_STEP_ISR_ENTRY2(checkCounter, __ss_end)
```

Some observations I made:
- The instruction that causes the violation is `MOV @r1+, r7` (`pop r7`) called from `__unprotected_stub_dummy`. The value of `r1` at this point is `6f5c`.
- At the end of the previous cycle, this same instruction is executed with `r1` being `41F6`. One cycle before, the value is again `41F6`. (It seems like for every cycle but the last, this is consistent.)
- The instruction that restores the value of `r1` prior to this instruction is in `__unprotected_stub_dummy`. For some reason, when this instruction executes in the 9th cycle, it does not restore the value that was previously stored in it. The value loaded in the last cycle is `6F60`, this value never occurs in `r1` before this point (as far as I can tell). Maybe this load gets corrupted by the IRQ? Or something overflows this memory location? I'm not sure why else this value would be loaded.
- I also tracked the value of the stack pointer in the protected module for each cycle. For each cycle, it looks like the following:

  | Cycle | Start | End |
  |---------|--------|-------|
  | 1 | 08c4 | 08c4 |
  | 2 | 08a8 | 08a8 |
  | 8 | 0800 | 0800 |
  | 9 | 07e4 | 07e4 |

I uploaded both the object dump and the waveform of the simulation [here](https://www.dropbox.com/s/8hr1t6jr5ujqbge/violation.zip?dl=0).

**Comment by jovanbulck** [comment]
thanks for the detailed and helpful report! I just went through the trace and pin-pointed the problem I think: 

* the crash happens at `unprotected_stub_dummy` after returning from the enclave, but going back before that the previously saved value at `__unprotected_sp` was corrupted by the IRQ logic when the in-enclave stack overflowed beyond `__sm_foo_secret_start`
* your table already shows the root cause of the problem: after every enclave entry with  sancus-step, the in-enclave stack is decreased (instead of being properly restored to stack_init) and will eventually overflow into unprotected memory

Hence, the fix would be to prob add a `dint` somewhere so that the stack is cleared to `sm_stack_init` on exit. I'll look into that in a moment, but more generally there's also [hardware support](https://github.com/sancus-pma/sancus-core/blob/master/core/sim/rtl_sim/src/sancus/stack_guard.s43) to detect such implicit stack overflows, which we'd better merge into the compiler support as well

**Comment by martonbognar** [comment]
I'll also look into properly restoring the stack, I just wasn't sure before (based on the trace) that that is the actual cause of the problem.

**Comment by jovanbulck** [comment]
okay Im testing a simple patch now in the simulator and will push once it seems to be working (but you should test it on the FPGA since I don't have an IRQ-enabled Sancus FPGA here atm).

I think it makes sense to add support for the "stack-guard" instruction in `sm_entry.s` as well. If you want to have a look: this should be relatively straightforward/feasible when looking at the HW/SW contract [here](https://github.com/sancus-pma/sancus-core/blob/master/core/sim/rtl_sim/src/sancus/stack_guard.s43) and [here](https://github.com/sancus-pma/sancus-core/blob/master/core/sim/rtl_sim/src/sancus/sancus_macros.asm#L14) and then have a look at the [linker script](https://github.com/sancus-pma/sancus-compiler/blob/master/src/drivers/linker.py#L596) to see how you can parameterize the configure enclave-private stack size, which you'll need to pass to the stack-guard instruction..

**Comment by jovanbulck** [comment]
I added a patch in the sancus-compiler repo: can you please try to apply this and verify whether it fixes the issue on the FPGA?

**Comment by martonbognar** [comment]
It seems like the issue is fixed, at least this minimal example runs without a violation!

Thanks, I'll try running a more elaborate example (bsl from Nemesis), if I run into something, I'll get back to this issue.
